### PR TITLE
Support for prettier provided

### PR DESCRIPTION
**Pull request by 16sweetyjain**

### CODE REVIEW

**Comment by elit-altum** [comment]
@16sweetyjain Do you want this PR to count for Hacktober? If that's the case I'll merge it on October 1st.

**Comment by 16sweetyjain** [comment]
@elit-altum yes merge it on Oct 1.

**Review by elit-altum — APPROVED** [review]

**Comment by elit-altum** [comment]
Please update the PR by complying with [these guidelines](https://github.com/elit-altum/AuthExp-Express-Starter/blob/master/CONTRIBUTING.md)
Always read the ```CONTRIBUTING.md``` of any repo before contributing to it.

**Comment by 16sweetyjain** [comment]
Sure will do that @elit-altum

**Pull request closed without merging**
